/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e2e2e2",
        "surface-bright": "#f9f9f9",
        "tertiary-container": "#1b1c1c",
        "on-secondary-container": "#745c00",
        "surface-container-highest": "#e2e2e2",
        "on-secondary-fixed": "#241a00",
        "primary-container": "#1c1b1b",
        "inverse-primary": "#c8c6c5",
        "surface": "#f9f9f9",
        "on-tertiary-fixed": "#1b1c1c",
        "surface-dim": "#dadada",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "primary": "#000000",
        "background": "#f9f9f9",
        "inverse-surface": "#2f3131",
        "on-primary-fixed": "#1c1b1b",
        "secondary": "#A4000B",
        "accent": "#A4000B",
        "inverse-on-surface": "#f1f1f1",
        "on-tertiary-fixed-variant": "#464747",
        "on-surface-variant": "#444748",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "outline": "#747878",
        "surface-container": "#eeeeee",
        "tertiary-fixed": "#e3e2e2",
        "surface-container-high": "#e8e8e8",
        "on-surface": "#1a1c1c",
        "on-primary-fixed-variant": "#474746",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#c7c6c6",
        "surface-container-low": "#f3f3f3",
        "tertiary": "#000000",
        "on-error-container": "#93000a",
        "on-background": "#1a1c1c",
        "on-tertiary-container": "#848484",
        "secondary-container": "#F5A5A5",
        "outline-variant": "#c4c7c7",
        "secondary-fixed-dim": "#C91C22",
        "on-primary-container": "#858383",
        "primary-fixed": "#e5e2e1",
        "surface-tint": "#5f5e5e",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#6B0D13",
        "primary-fixed-dim": "#c8c6c5",
        "secondary-fixed": "#DC3545"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "24px",
        "stack-lg": "48px",
        "margin-desktop": "48px",
        "gutter": "24px",
        "unit": "8px",
        "stack-sm": "12px",
        "margin-mobile": "16px",
        "container-max-width": "1280px"
      },
      fontFamily: {
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "display-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "display-lg": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
};

